# Generated by Django 3.0.3 on 2020-03-28 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=20, verbose_name='Фамилия')),
                ('status', models.CharField(blank=True, choices=[('Новый покупатель', 'Новый покупатель'), ('Оптовый покупатель', 'Оптовый покупатель')], max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='Населённый пункт')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Почтовый индекс')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='Номер телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ('user',),
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
