# Generated by Django 3.0.3 on 2020-03-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('code',), 'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
    ]
