# Generated by Django 3.0.3 on 2020-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200406_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='flavour',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='flavour',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=10, null=True, verbose_name='Цена ранее(должна быть больше!'),
        ),
        migrations.AddField(
            model_name='flavour',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Закупочная цена'),
        ),
    ]
