# Generated by Django 3.0.3 on 2020-03-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200307_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(default='1', max_length=100, verbose_name='Позиция в списке категорий'),
        ),
    ]
