# Generated by Django 3.0.3 on 2020-03-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200308_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('position',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='offer',
            name='calc',
            field=models.CharField(default='', max_length=100, verbose_name='Для калькулятора'),
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(default='1', verbose_name='Позиция в списке категорий'),
        ),
    ]
