# Generated by Django 3.0.3 on 2020-04-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200406_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='price',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Цена ранее(должна быть больше!'),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=10, verbose_name='Закупочная цена'),
        ),
    ]
