# Generated by Django 3.0.3 on 2020-03-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200309_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ('email',),
            },
        ),
        migrations.AlterField(
            model_name='offer',
            name='calc',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Для калькулятора'),
        ),
    ]
