# Generated by Django 3.0.6 on 2020-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200512_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_time',
            field=models.CharField(blank=True, max_length=20, verbose_name='Время доступа'),
        ),
    ]
