# Generated by Django 3.0.6 on 2020-05-26 16:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_available_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_time',
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'verbose_name': 'Подписка на товар',
                'verbose_name_plural': 'Подписки на товар',
                'ordering': ('id',),
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
