# Generated by Django 3.0.6 on 2020-07-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200527_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
