# Generated by Django 3.0.3 on 2020-03-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='braintree_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=250, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver',
            field=models.CharField(choices=[('Почта России', 'Почта России'), ('СДЭК', 'СДЭК'), ('Деловые линии', 'Деловые линии'), ('ПЭК', 'ПЭК'), ('Другое (комментарий)', 'Другое (комментарий)')], max_length=50, verbose_name='Перевозчик'),
        ),
    ]
