# Generated by Django 3.0.6 on 2020-06-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200530_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_number',
            field=models.CharField(default=' ', max_length=50, verbose_name='Номер отслеживания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Новый', 'Новый'), ('В работе', 'В работе'), ('Отправлен', 'Отправлен'), ('Выполнен', 'Выполнен'), ('Отказ', 'Отказ')], max_length=50, verbose_name='Статус'),
        ),
    ]
