# Generated by Django 3.0.6 on 2020-07-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200607_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_mass',
            field=models.IntegerField(default=2000, verbose_name='Масса заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='Пермь', max_length=100, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='track_number',
            field=models.CharField(blank=True, default=' ', max_length=50, verbose_name='Номер отслеживания'),
        ),
    ]
